"""
api/main.py — FastAPI application entry point.

Start the server:
    uvicorn api.main:app --reload --port 8000

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs       ← Swagger UI
    http://localhost:8000/redoc      ← ReDoc
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from api.routers import predict as predict_router
from src.config import MODELS_DIR, TICKERS, model_path

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)


# ── Startup / shutdown lifecycle ──────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs once on startup (before the first request) and once on shutdown.

    Startup checks:
      - Verifies that all 5 .joblib model artifacts exist on disk.
      - Logs a warning for any missing models so the issue is visible
        immediately rather than surfacing only when a request arrives.

    This does NOT pre-load models into memory — each request loads
    its model fresh via joblib.load(). For a high-throughput production
    server you would cache models here; for this project the latency
    is acceptable and keeps memory usage low.
    """
    logger.info("EGX Analyst API — starting up")
    logger.info(f"Models directory : {MODELS_DIR.resolve()}")

    missing = []
    for ticker in TICKERS:
        path = model_path(ticker)
        if path.exists():
            logger.info(f"  ✓ {ticker} model found  ({path.name})")
        else:
            logger.warning(f"  ✗ {ticker} model MISSING — run 'python -m src.train'")
            missing.append(ticker)

    if missing:
        logger.warning(
            f"{len(missing)} model(s) not found: {missing}. "
            "Predictions for these tickers will return 503 until models are trained."
        )
    else:
        logger.info("All 5 models present — ready to serve predictions.")

    yield  # application runs here

    logger.info("EGX Analyst API — shutting down")


# ── Application factory ───────────────────────────────────────────────────────

def create_app() -> FastAPI:
    """
    Create and configure the FastAPI application.

    Separated into a factory function so tests can call create_app()
    without importing a module-level app object that has side effects.
    """
    app = FastAPI(
        title="EGX Analyst API",
        description=(
            "Next-day directional price prediction for 5 major Egyptian Exchange (EGX) stocks. "
            "Each prediction combines a classical ML model (XGBoost / LightGBM / RandomForest) "
            "with a 20-feature scale-invariant technical analysis pipeline. "
            "Predictions are consumed by the LangGraph agent layer for news-augmented analysis."
        ),
        version="1.0.0",
        contact={
            "name": "EGX Analyst",
        },
        lifespan=lifespan,
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # ── CORS ──────────────────────────────────────────────────────────────────
    # Allows the Streamlit UI (running on a different port) and the
    # LangGraph agent to call the API without browser CORS errors.
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],   # tighten to specific origins in production
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # ── Routers ───────────────────────────────────────────────────────────────
    app.include_router(predict_router.router)

    # ── Root ──────────────────────────────────────────────────────────────────
    @app.get("/", include_in_schema=False)
    async def root():
        return {
            "service": "EGX Analyst API",
            "version": "1.0.0",
            "docs":    "/docs",
            "health":  "/health",
        }

    # ── Health check ──────────────────────────────────────────────────────────
    @app.get(
        "/health",
        tags=["System"],
        summary="API health check",
        description="Returns service status and confirms which model artifacts are present.",
    )
    async def health():
        model_status = {}
        all_present  = True
        for ticker in TICKERS:
            exists = model_path(ticker).exists()
            model_status[ticker] = "ready" if exists else "missing"
            if not exists:
                all_present = False

        return JSONResponse(
            status_code=200,
            content={
                "status":        "ok",
                "models_loaded": all_present,
                "model_status":  model_status,
                "tickers":       TICKERS,
            },
        )

    return app


# ── Module-level app instance (used by uvicorn) ───────────────────────────────
app = create_app()
